package cs203t10.ryver.cms.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import cs203t10.ryver.cms.content.Content;
import cs203t10.ryver.cms.content.ContentRepository;
import cs203t10.ryver.cms.content.ContentService;
@Component
@Order(2)
public class DefaultContents implements CommandLineRunner {

    @Autowired
    private ContentService contentService;

    
    /*
    Content item info:
        {
            "id": (auto-generated by your api, int value),
            "title":"The title of the advisory or news",
            "summary":"The short summary of the content item",
            "content": "The text of the content item",
            "link":"https://link.to.externalcontent",
            "approved": true (or false)
        }
     */

    @Override
    public void run(String... args) throws Exception {
        addDefaultContent(Content.builder().title("Post 1").summary("Post 1 is about Post 1").content("Post 1 has a lot to say about Post 1").approved(true).build());
        addDefaultContent(Content.builder().title("Post 2").summary("Post 2 is about Post 2").content("Post 2 has not much to say about Post 2").approved(true).build());
        addDefaultContent(Content.builder().title("Post 3").summary("Post 3 is not approved").content("Post 3 is not approved!").approved(false).build());
    }

    public void addDefaultContent(Content content) {
        contentService.addContent(content);
        System.out.println("[Add content]: " + content.getTitle());
    }
}

