server:
  port: 8082
  error:
    include-stacktrace: never

spring:
  application:
    name: ryver-cms
  datasource:
    url: jdbc:h2:file:./data/content;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761}/eureka
  instance:
    prefer-ip-address: true

