###
GET http://localhost:8082/


###
GET http://localhost:8082/contents
Accept: application/json

###
GET http://localhost:8082/contents
Accept: application/json
# Token generated with manager account.
Authorization: Bearer ...

###
GET http://localhost:8082/contents/
Accept: application/json
# Token generated with analyst account.
Authorization: Bearer ...

